framework:
    cache:
        # Définit le cache par défaut (équivalent de 'default' dans Laravel)
        default_redis_provider: '%env(REDIS_URL)%'
        app: cache.adapter.redis
        system: cache.adapter.system

        # Configuration des pools de cache (équivalent de 'stores' dans Laravel)
        pools:
            cache.apc:
                adapter: cache.adapter.apcu
            cache.array:
                adapter: cache.adapter.array
            cache.file:
                adapter: cache.adapter.filesystem
                provider: null
            cache.database:
                adapter: cache.adapter.doctrine
                provider: null
            cache.memcached:
                adapter: cache.adapter.memcached
                provider: '%env(MEMCACHED_DSN)%'
            cache.redis:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
            cache.dynamodb:
                adapter: cache.adapter.custom
                provider: '%env(DYNAMODB_URL)%'

    # Préfixe des clés de cache (équivalent de 'prefix' dans Laravel)
    cache_prefix: '%env(CACHE_PREFIX)%'
