SELECT U.GENDER,
       U.FIRST_NAME,
       U.LAST_NAME,
       U.EMAIL,
       A.LINE1,
       A.LINE2,
       A.DETAILS,
       CT.ZIPCODE,
       CT.NAME,
       CO.NAME
FROM "USER" AS U
         INNER JOIN USER_ADDRESS AS UA ON UA.USER_ID = U.ID
         INNER JOIN ADDRESS AS A ON UA.ADDRESS_ID = A.ID
         INNER JOIN CITY AS CT ON A.CITY_ID = CT.ID
         INNER JOIN COUNTRY AS CO ON CT.COUNTRY_CODE = CO.CODE
